### ISSUE TITLE
Store users location as location in user table

### ISSUE THREAD

**Issue by michelleambrisco** [tleskin/meetup-matcher#31]

**Comment by michelleambrisco** [comment]
Maybe we should remove the location field and change it to lat and lon?

**Comment by MLee21** [comment]
We don't even need that field, because we're using javascript to get the geolocation of a user after they authenticate through twitter. We could remove that column if we want to since we're not requesting their location through twitter.

**Comment by michelleambrisco** [comment]
Gotcha, I assumed it would still be stored in the database but if we can reference it as is that's perfect.
